import Head from 'next/head'; 

interface ICustomHead {
  title: string,
  description?: string
}

export const CustomHead = (props: ICustomHead) => {
  const { title } = {...props}
    return (
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
};